name: tekko
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.6.0

dependencies:
  animate_do: ^4.2.0
  another_flutter_splash_screen: ^1.2.1
  audioplayers: ^5.2.1
  awesome_calendart: ^1.2.1
  bloc: ^9.0.0
  card_game: ^1.1.1
  curved_navigation_bar: ^1.0.6
  dio: ^5.8.0+1
  equatable: ^2.0.7
  flame: ^1.24.0
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.0
  flutter_datetime_picker_plus: ^2.2.0
  flutter_dotenv: ^5.2.1
  flutter_hooks: ^0.21.2
  flutter_stripe: ^9.4.0
  gal: ^2.3.1
  go_router: ^14.6.3
  hugeicons: ^0.0.7
  intl: ^0.20.2
  lottie: ^3.3.0
  meta: ^1.15.0
  path_provider: ^2.1.5
  shared_preferences: ^2.5.2
  url_launcher: ^6.3.1
  vibration: ^3.1.2

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/animations/
    - assets/images/
    - assets/images/bgsplash.png
    - assets/images/words/conversacion/
    - assets/sounds/conversacion/
    - assets/images/words/ropas/
    - assets/sounds/ropas/
    - assets/images/activities/
    - assets/images/words/familia/
    - assets/sounds/familia/
    - assets/images/words/alimentos/
    - assets/sounds/alimentos/
    - assets/images/words/juegos/
    - assets/sounds/juegos/
    - assets/images/words/animales/
    - assets/sounds/animales/
    - assets/sounds/nivel/
    - .env
    - assets/images/words/acciones/
    - assets/sounds/acciones/
    - assets/images/words/emociones/
    - assets/sounds/emociones/
    - assets/images/words/escuela/
    - assets/sounds/escuela/
    - assets/images/words/transporte/
    - assets/sounds/transporte/
    - assets/images/words/comidas/
    - assets/sounds/comidas/
    - assets/images/words/frases/
    - assets/sounds/frases/
    - assets/images/words/lugares/
    - assets/sounds/lugares/
    - assets/images/words/clima/
    - assets/sounds/clima/
    - assets/images/words/objetos/
    - assets/sounds/objetos/
