name: tekko
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.6.0

dependencies:
  another_flutter_splash_screen: ^1.2.1
  audioplayers: ^5.2.1
  curved_navigation_bar: ^1.0.6
  flame: ^1.24.0
  flutter:
    sdk: flutter
  go_router: ^14.6.3
  hugeicons: ^0.0.7
  lottie: ^3.3.0
  shared_preferences: ^2.5.2
  vibration: ^3.1.2

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/animations/
    - assets/images/
    - assets/images/words/conversacion/
    - assets/sounds/conversacion/
    - assets/images/words/ropas/
    - assets/sounds/ropas/
    - assets/images/activities/
